
# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs


## Uses Go Regex

## Labels

labels:

  CR:
    include:
      - 'CR'
      - '(?i)Change Request'
  'Urgent :bangbang:':
    include:
      - '(?i)Urgent'
  Deployment:
    include: 
      - '(?i)Deployment'
  Req. Design:
    include:
      - '(?i)have to design'
      - '(?i)needs design'
      - '(?i)requires design'

## Product Labels
  Product - POMA:
    include:
      - '(?i)#\s*Product[^\r\n]*POMA\b'
  Product - Gateway:
    include:
      - '(?i)#\s*Product[^\r\n]*Gateway\b'
  Product - POM:
    include:
      - '(?i)#\s*Product[^\r\n]*POM\b'
  Product - POH:
    include:
      - '(?i)#\s*Product[^\r\n]*POH\b'
  Product - Spotbid:
    include:
      - '(?i)#\s*Product[^\r\n]*Spotbid\b'
  Product - Connecting Shop:
    include:
      - '(?i)#\s*Product[^\r\n]*(Connecting[^\w\r\n]+)?Shop\b'
  Product - Connecting Prodrisk:
    include:
      - '(?i)#\s*Product[^\r\n]*Prodrisk\b'
  Product - Optimal Log:
    include:
      - '(?i)#\s*Product[^\r\n]*(Optimal[^\w\r\n]+)?log\b'
  Product - Battery:
    include:
      - '(?i)#\s*Product[^\r\n]*Battery\b'

## Severity Labels
  'Severity - Critical :boom:':
    include:
      - '(?i)Severity[^\w\r\n]*Critical'
  'Severity - Major :boom:':
    include:
      - '(?i)Severity[^\w\r\n]*Major'
  'Severity - Average :broken_heart:':
    include:
      - '(?i)Severity[^\w\r\n]*Average'
  'Severity - Minor :construction:':
    include:
      - '(?i)Severity[^\w\r\n]*Minor'

## Customer Labels
  'Customer - Enel':
    include:
      - '(?i)Customer[^\w\r\n]*Enel'
  'Customer - EPC':
    include:
      - '(?i)Customer[^\w\r\n]*EPC'
  'Customer - Luminus':
    include:
      - '(?i)Customer[^\w\r\n]*Luminus'
  'Customer - Uniper':
    include:
      - '(?i)Customer[^\w\r\n]*Uniper'
  'Customer - Iberdrola':
    include:
      - '(?i)Customer[^\w\r\n]*Iberdrola'
  'Customer - A2A':
    include:
      - '(?i)Customer[^\w\r\n]*A2A'

## Version Labels
  'v1.5.0':
    include:
      - '(?i)v?\s*1(\.|,)5((\.|,)0|\s|$)'
  'v1.6.0':
    include:
      - '(?i)v?\s*1(\.|,)6((\.|,)0|\s|$)'
  'v1.7.0':
    include:
      - '(?i)v?\s*1(\.|,)7((\.|,)0|\s|$)'
  'v1.8.0':
    include:
      - '(?i)v?\s*1(\.|,)8((\.|,)0|\s|$)'
  'v1.9.0':
    include:
      - '(?i)v?\s*1(\.|,)9((\.|,)0|\s|$)'
  'v1.10.0':
    include:
      - '(?i)v?\s*1(\.|,)10((\.|,)0|\s|$)'
  'v1.11.0':
    include:
      - '(?i)v?\s*1(\.|,)11((\.|,)0|\s|$)'
  'develop':
    include:
    - '(?i)Version:[^\n\r]*v?\s*develop'
