name: "Issue - Labled: Transfer"

on:
  issues:
    types:
      - labeled


jobs:
  transfer_issue:
    name: transfer issue
    if: ${{ !contains(github.event.issue.labels, '[X] Transfered') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        router:
          - Product - POMA:TestRepo
          - Product - SHOP:TestRepo
    steps:
    - name: Transfer Issue & Comment
      uses: lando/transfer-issue-action@v2
      id: transfer-issue
      with:
        token: ${{ secrets.OPT_GH_TOKEN }}
        router: ${{ matrix.router }}
        debug: true
        create_stub: true
