name: "Issue - Labled: Transfer"

on:
  issues:
    types:
      - labeled

env:
  PROTECTED_JSON: '{ "Product - POMA\\b" : "true" }'
  TRANSFER_MAP: '{ 
          "Product - POMA\\b" : "labelOnPRReview",
          "Product - Gateway\\b" : "TestRepo",
          "Product - POM\\b" : "TestRepo",
          "Product - POH\\b" : "TestRepo",
          "Product - Spotbid\\b" : "false",
          "Product - Connecting Shop\\b" : "TestRepo",
          "Product - Connecting Prodrisk\\b" : "TestRepo",
          "Product - Optimal Log\\b" : "TestRepo"
        }'

jobs:

  check_time:
    name: check Time
    if: ${{ contains(github.event.label.name, 'Product') && !github.event.issue.locked && github.event.issue.state != 'closed' }}
    runs-on: ubuntu-latest
    steps:
    - name: Get Current Issue State
      uses: octokit/request-action@v2.x
      id: get_body
      with:
        route: GET /repos/${{github.repository}}/issues/${{github.event.issue.number}}      
      env:
        GITHUB_TOKEN: ${{ secrets.OPT_GH_TOKEN }}

    - name: Check Time
      id: time
      shell: bash
      run: |
        created=$(date -d "${{fromJson(steps.get_body.outputs.data).created_at}}" +"%s")
        now=$(date -d now +"%s")
        diff=$(($now - $created))
        echo $diff
        if [[ $diff > 600 ]]; then
          echo ::set-output name=after::true
        else
          echo ::set-output name=after::false
        fi
    outputs:
      transfer: ${{ steps.time.outputs.after }}
      issue: fromJson(steps.get_body.outputs.data)


  transfer_issue:
    needs: check_time
    if: ${{ needs.check_time.outputs.transfer == 'true' }}
    name: transfer issue
    runs-on: ubuntu-latest
    steps:
## Check if any labels are protected

    - name: Check Protection
      id: protect
      uses: ChristofferDahlen/Multi-Regex-Match@v1.0
      with:
        input: "${{toJson(fromJson(steps.get_body.outputs.data).labels.*.name) }}"
        json_match: ${{ env.PROTECTED_JSON }}


## Match label with repo
    - name: Match Label
      if: steps.protect.outputs.result != true 
      id: match
      uses: ChristofferDahlen/Multi-Regex-Match@v1.0
      with:
        input: "${{ github.event.label.name }}"
        json_match: ${{ env.TRANSFER_MAP }}
    - run: |
          if [[ "${{ needs.check_time.outputs.transfer.state}}" == "closed" ||"${{github.repository_owner}}/${{ steps.match.outputs.result }}" == "${{ github.repository }}" ||  "${{ steps.match.outputs.result }}" == "" || "${{ steps.match.outputs.result }}" == "false"  ]]
          then
            echo ::set-output name=remain::true
          else
            echo ::set-output name=remain::false
          fi
      shell: bash
      name: Check if we should move from ${{ github.repository }} to ${{ steps.match.outputs.result }}
      id: state

    - name: Transfer Issue & Comment
      if: steps.state.outputs.remain == 'false' && steps.time.outputs.after == 'true'
      uses: christofferDahlen/transfer-issue-action@v3
      with:
        target_repo: ${{ steps.match.outputs.result }}
        token: '${{ secrets.OPT_GH_TOKEN }}'
        debug: true
        create_stub: true
